# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias zz='source ~/.bashrc'
alias mroe='more'
alias h=history
alias qt47='source ~/bin/setq47'
alias qtsim='source ~/bin/setqsim'
alias bashqt47='bash --rcfile ~/bin/initqt47'
alias bashqtsim='bash --rcfile ~/bin/initqtsim'
export EXTRA_PATH="/usr/local/bin"
export PATH="$EXTRA_PATH:$PATH"

