# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
umask 0022


# User specific aliases and functions

alias zz='source ~/.bashrc'
alias mroe='more'
alias h=history
alias qt47='source ~/bin/setq47'
alias qtsim='source ~/bin/setqsim'
alias bashqt47='bash --rcfile ~/bin/initqt47'
alias bashqtsim='bash --rcfile ~/bin/initqtsim'
alias meeosc='osc -A https://api.pub.meego.com'

alias fdt='float deeptrim'
export QTDIR="/usr/lib64/qt4"
export QT_SOURCE_TREE="/home/bernd/Downloads/software/qt-source/qt-everywhere-opensource-src-4.7.1"
export HOME_LOCAL="$HOME/local"
#export QT_CREATOR_DIR="$HOME_LOCAL/qtcreator-2.1.0"
#export QT_CREATOR_LIBDIR="$QT_CREATOR_DIR/lib"
export EXTRA_PATH="$HOME_LOCAL/bin:/usr/local/bin"
export PATH="$EXTRA_PATH:$PATH"
export LD_LIBRARY_PATH="/usr/local/lib"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
export EDITOR='vi'

export PACK="${HOME}/packaging"
export OSCPACK="${HOME}/osc-packing"
export MEEPACK="${HOME}/meego-packing"

export MAKEFLAGS="-j2"

export PS1='\u@\h \t \W \$ '


