#!/bin/bash
#set -x
IMAGEFILE="$HOME/.config/backgrounds/images"
IMAGES=`cat $IMAGEFILE`
NEW_IMAGE=`randarg $IMAGES `
GCONF_KEY="/desktop/gnome/background/picture_filename"
GSETTINGS_KEY="picture-uri"
GSETTINGS_SCHEMA="org.gnome.desktop.background"
GSETTINGS_URI="file://"${NEW_IMAGE}
if [ -e ${NEW_IMAGE} ]
then
  #gconftool-2 --type=string --set $GCONF_KEY  $NEW_IMAGE
  gsettings set ${GSETTINGS_SCHEMA} ${GSETTINGS_KEY} ${GSETTINGS_URI}
else
  echo "no file $NOW_IMAGE"
fi
