#!/bin/bash
#set -x
IMAGEFILE="$HOME/.config/backgrounds/images"
IMAGES=`cat $IMAGEFILE`
NEW_IMAGE=`randarg $IMAGES `
GCONF_KEY="/desktop/gnome/background/picture_filename"
if [ -e $NEW_IMAGE ]
then
  gconftool-2 --type=string --set $GCONF_KEY  $NEW_IMAGE
else
  echo "no file $NOW_IMAGE"
fi
