#!/bin/bash
if [ $# > 1 ]
then
  branch=$1
else
  branch=master
fi
for tgt in `git remote show`
do
  if [ X${tgt} == "usbstick" ]
  then
    echo "Push to -- " ${tgt} " -- Skipped"
  else
    echo "Push to -----------> " ${tgt}
    git push ${tgt} ${branch}
  fi
done
