#!/bin/bash

DELAY=10

for R in 1 # 2 3
do
  ip addr | grep inet | grep global
  if [ $? -eq 1 ]; then
    echo "no network connection, pointless to start aiccu"
    break
  fi

  ip addr | grep inet6 | grep global
  if [ $? -eq 1 ]; then
    echo "try to start aiccu"
    systemctl start aiccu.service
  else
    echo "have ipv6 global link"
    break
  fi
  sleep $DELAY
done
ip addr | grep global
