#!/bin/bash

DELAY=10

for R in 1 2
do
  ip addr | grep inet6 | grep global
  if [ $? -eq 1 ]; then
    echo "try to start aiccu"
    systemctl start aiccu.service
  else
    echo "have ipv6 global link"
    break
  fi
  sleep $DELAY
done
